site_name: JUJUnotebook
theme:
  name: readthedocs
  highlightjs: true
  include_homepage_in_sidebar: true
plugins:
  - search
  - encryptcontent
  # - mkdocstrings:


markdown_extensions:
  - toc
  - admonition # to use rendering block like rst

